# Generated by Django 3.1.4 on 2021-01-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
